TsDoc comments show up in output (#12)
* CI: check for TsDoc comments

* Keep comments

diff --git a/.azure/pipelines/jobs/build_and_test.yml b/.azure/pipelines/jobs/build_and_test.yml
--- a/.azure/pipelines/jobs/build_and_test.yml
+++ b/.azure/pipelines/jobs/build_and_test.yml
@@ -66,3 +66,23 @@ jobs:
       - publish: doc
         condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
         artifact: docs
+
+      - bash: |
+          cd lib
+
+          count=0
+
+          for dts in **/*.d.ts; do
+              tmp=$(cat $dts | grep "@param" | wc -l)
+              echo "$dts: $tmp matches"
+              ((count+=tmp))
+          done
+
+          echo ""
+          echo "matches: $count"
+
+          if [[ $count == 0 ]]; then
+              echo "##vso[task.logissue type=error]there should be at least one @param in the d.ts files"
+              exit 1
+          fi
+        displayName: check for TsDoc comments
